In [2]:
import pandas as pd
import numpy as np


data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital_Status": ["Single", "Married", "Single", "Married", "Divorced",
                        "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable_Income": ["125K", "100K", "70K", "120K", "95K", "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df

   Tid Refund Marital_Status Taxable_Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Q2

In [3]:
rows_needed = df.loc[[0, 4, 7, 8]]
rows_needed

   Tid Refund Marital_Status Taxable_Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q3

In [4]:
part1 = df.iloc[3:8]
part1

   Tid Refund Marital_Status Taxable_Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

In [5]:
part2 = df.iloc[4:9, 2:5]
part2

  Marital_Status Taxable_Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

In [6]:
part3 = df.iloc[:, 1:4]
part3

  Refund Marital_Status Taxable_Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q4

In [7]:
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
iris_df = iris.frame
iris_df.to_csv("iris.csv", index=False)

print("iris.csv file created!")

iris.csv file created!

In [8]:
iris_df = pd.read_csv("iris.csv")

iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

## Q5

In [9]:
new_iris = iris_df.drop(index=4)

col_to_drop = iris_df.columns[3]
new_iris = new_iris.drop(columns=col_to_drop)

new_iris.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  target
0                5.1               3.5                1.4       0
1                4.9               3.0                1.4       0
2                4.7               3.2                1.3       0
3                4.6               3.1                1.5       0
5                5.4               3.9                1.7       0

## Q6

In [10]:
emp_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

emp_df = pd.DataFrame(emp_data)
emp_df.to_csv("employees.csv", index=False)

emp = pd.read_csv("employees.csv")
emp

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [ ]:
print("Shape of the dataset (rows, columns):", emp.shape)

In [ ]:
emp.info()

In [ ]:
emp.describe()

In [ ]:
print("First 5 rows:")
print(emp.head())

print("\nLast 3 rows:")
print(emp.tail(3))

In [11]:
avg_salary = emp["Salary"].mean()
print("Average Salary:", avg_salary)

total_bonus = emp["Bonus"].sum()
print("Total Bonus paid:", total_bonus)

youngest_age = emp["Age"].min()
print("Youngest employee age:", youngest_age)


highest_rating = emp["Rating"].max()
print("Highest Rating:", highest_rating)

Average Salary: 60000.0
Total Bonus paid: 27500
Youngest employee age: 28
Highest Rating: 4.7

In [12]:
sorted_emp = emp.sort_values(by="Salary", ascending=False)
sorted_emp

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [13]:
def get_performance(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

emp["Performance"] = emp["Rating"].apply(get_performance)
emp

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [14]:
emp.isnull().sum()

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

In [ ]:
emp = emp.rename(columns={"Employee_ID": "ID"})
emp.head()

In [15]:
exp_more_than_5 = emp[emp["Years_of_Experience"] > 5]
print("Employees with more than 5 years experience:")
print(exp_more_than_5)


it_dept = emp[emp["Department"] == "IT"]
print("\nEmployees in IT department:")
print(it_dept)

Employees with more than 5 years experience:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12

  Joining_Date Gender  Bonus  Rating Performance
1   2017-07-19   Male   7000     4.0        Good
2   2013-06-01   Male   6000     3.8     Average
4   2010-11-25   Male   5000     3.5     Average

Employees in IT department:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10

  Joining_Date Gender  Bonus  Rating Performance
1   2017-07-19   Male   7000     4.0        Good
2   2013-06-01   Male   6000     3.8     Average

In [ ]:
emp["Tax"] = emp["Salary"] * 0.10
emp

In [ ]:
emp.to_csv("employees_modified.csv", index=False)
print("Saved successfully as employees_modified.csv")